### ISSUE TITLE
can't import clusterByGrid

### ISSUE THREAD

**Issue by sunic3** [fede4ka1245/ymap3-components#1]
Can u add some utilities, for example [clusterByGrid](https://yandex.ru/dev/jsapi30/doc/ru/ref/packages/clusterer/#) pls 😊

**Comment by fede4ka1245** [comment]
Hey! Can add that only via context api.

The problem is that api uses context to render components, and import won't work for utils. 
So, Only can add via context api.

For now you can use `reactify` and `ymaps` from `onLoad` method in `YMapComponentsProvider` to load utils like that provided in their docs!

**Comment by fede4ka1245** [comment]
Hello! 

There is official library `@yandex/ymaps3-clusterer`: https://www.npmjs.com/package/@yandex/ymaps3-clusterer. You can import [clusterByGrid](https://yandex.ru/dev/jsapi30/doc/ru/ref/packages/clusterer/#) from here!

Just like that: `import { clusterByGrid } from "@yandex/ymaps3-clusterer";`

**Comment by TequilaJohnny** [comment]
Hello, can you please help me with clusterer? I tried to use official library @yandex/ymaps3-clusterer and i am getting an Error:
`ymaps3 is not defined
ReferenceError: ymaps3 is not defined
    at ./node_modules/@yandex/ymaps3-clusterer/dist/esm/YMapClusterer/YMapClusterer.js (http://localhost:3001/static/js/bundle.js:79967:29)
    at options.factory (http://localhost:3001/static/js/bundle.js:208027:31)
    at __webpack_require__ (http://localhost:3001/static/js/bundle.js:207450:33)
    at fn (http://localhost:3001/static/js/bundle.js:207684:21)
    at ./node_modules/@yandex/ymaps3-clusterer/dist/esm/YMapClusterer/index.js (http://localhost:3001/static/js/bundle.js:80239:72)
    at options.factory (http://localhost:3001/static/js/bundle.js:208027:31)
    at __webpack_require__ (http://localhost:3001/static/js/bundle.js:207450:33)
    at fn (http://localhost:3001/static/js/bundle.js:207684:21)
    at ./node_modules/@yandex/ymaps3-clusterer/dist/esm/index.js (http://localhost:3001/static/js/bundle.js:80462:78)
    at options.factory (http://localhost:3001/static/js/bundle.js:208027:31)`

**Comment by TequilaJohnny** [comment]
My source code is 
`const MapContainer = ({ apikey, centerLocation, devices }) => {
  const ymap3Ref = useRef<YMaps.YMap>(null);
  const [clusterMethod, setClusterMethod] = useState(null);

  return(
    <YMapComponentsProvider 
      apiKey={apiKey}
      onLoad={({ ymaps }) => {
        const clusterMethod = ymaps.utils.clusterByGrid({gridSize: 64});
        setClusterMethod(clusterMethod);
    }}>
      <YMap 
        key="map"
        ref={ymap3Ref}
        location={location} 
        mode="vector"
        theme="dark"
      >
        <YMapDefaultSchemeLayer />
        <YMapDefaultFeaturesLayer />
       
        <YMapClusterer 
          method={clusterByGrid({gridSize: 64})}
          features={devices.map(device => ({
            type: 'Feature',
            id: device.id,
            geometry: {
              type: 'Point',
              coordinates: [device.lng, device.lat],
            },
          }))}
            
          marker={(feature) => (
            <YMapMarker
              coordinates={feature.geometry.coordinates}
              key={feature.id}
            >
              <>
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 80 80">
                <circle cx="40" cy="40" r="30" fill="none" stroke="#ff0000" stroke-width="4" />
                <circle cx="40" cy="40" r="20" fill="#ff0000">
                  <animate attributeName="opacity" values="0;1;0" dur="1.5s" repeatCount="indefinite" />
                </circle>
              </svg>
              </>
            </YMapMarker>
          )}

          cluster={(coordinates, features) => (
            <div>
              <p>Devices Count: {features.length}</p>
            </div>
          )}
        />
      </YMap>
    </YMapComponentsProvider>`

**Comment by TequilaJohnny** [comment]
Please can you show me how to use Clusterer in your library? Я уже в отчаянии

**Comment by fede4ka1245** [comment]
you still can use it via modules from official docs https://github.com/fede4ka1245/ymap3-components/issues/1#issuecomment-1879913725
